spring:
  application:
    name: shopapp
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Angular_SpringBoot;encrypt=true;trustServerCertificate=true
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: sa
    password: 123
    jpa:
      show-sql: true
      open-in-view: false
      hibernate:
        ddl-auto: none
      properties:
        hibernate:
          dialect: org.hibernate.dialect.SQLServerDialect
          format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
api:
  prefix: api/v1